{
  config,
  lib,
  user ? "taco",
  ...
}:

let
  cfg = config.taco.darwin.apps.home-server;
in
{
  # Design notes distilled from the original Mac home-server discussion:
  # - The data volume is expected to be a mirror, while backup lives on a
  #   separate disk. RAID reduces disk-failure downtime; it does not replace
  #   backup because deletion and corruption are mirrored too.
  # - SMB/Finder sharing plus PhotoSync is the primary iPhone ingest path.
  #   WebDAV can be added for simple remote access, but S3/SeaweedFS-style
  #   object storage is too indirect for a daily Mac file server.
  # - PiGallery2 is used as a lightweight, read-only viewer over existing
  #   folders. Immich remains an optional future step for full mobile backup,
  #   timeline, ML, and shared-album workflows.
  # - Jellyfin is kept for long-form and password-protected video viewing.
  #   It can show photos, but it is not a full photo manager.
  # - nix-darwin owns host packages, generated templates, and activation-time
  #   scaffolding. Heavier web apps belong in Docker Compose or native macOS
  #   apps; k3s adds VM, storage, ingress, and secret-management complexity
  #   that is not justified for this three-disk Mac server.
  # - Remote access should be Tailscale-first. Public Caddy exposure should be
  #   enabled only after TLS, authentication, and hostnames are chosen
  #   deliberately.
  options.taco.darwin.apps.home-server = {
    enable = lib.mkEnableOption "Mac home server dependencies and scaffolding";

    dataRoot = lib.mkOption {
      type = lib.types.str;
      default = "/Volumes/Data";
      description = "Primary data volume root for photos, videos, and files.";
    };

    backupRoot = lib.mkOption {
      type = lib.types.str;
      default = "/Volumes/Backup";
      description = "Backup volume root for backup repositories and copies.";
    };

    serviceRoot = lib.mkOption {
      type = lib.types.str;
      default = "/Users/${user}/home-server";
      description = "Writable home-server workspace for generated compose and service state.";
    };

    installJellyfinCask = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Install the Jellyfin macOS app with Homebrew Cask.";
    };

    startNetworkServices = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Start network-facing Homebrew services that are safe without app-specific secrets.";
    };
  };

  config = lib.mkIf cfg.enable {
    taco.darwin.apps.container-tools = {
      enable = true;
      startColimaService = true;
    };

    homebrew = {
      enable = true;
      brews = [
        {
          name = "tailscale";
          start_service = cfg.startNetworkServices;
        }
        "caddy"
        "ffmpeg"
        "filebrowser"
        "jq"
        "rclone"
        "restic"
        "rsync"
        "smartmontools"
        "yq"
      ];
      casks = lib.optionals cfg.installJellyfinCask [
        "jellyfin"
      ];
    };

    environment.etc."darwin-mac-home-server/compose.yaml".text = ''
      name: darwin-mac-home-server

      services:
        pigallery2:
          image: bpatrik/pigallery2:latest
          container_name: darwin-mac-home-server-pigallery2
          restart: unless-stopped
          ports:
            - "127.0.0.1:8082:80"
          volumes:
            - ${cfg.serviceRoot}/state/pigallery2/config:/app/data/config
            - ${cfg.serviceRoot}/state/pigallery2/db:/app/data/db
            - ${cfg.serviceRoot}/state/pigallery2/tmp:/app/data/tmp
            - ${cfg.dataRoot}/Photos:/app/data/images:ro
    '';

    environment.etc."darwin-mac-home-server/Caddyfile".text = ''
      {
        auto_https off
      }

      http://localhost:8080 {
        respond "darwin-mac-home-server is installed"
      }

      http://localhost:9081 {
        reverse_proxy 127.0.0.1:8096
      }

      http://localhost:9082 {
        reverse_proxy 127.0.0.1:8082
      }
    '';

    environment.etc."darwin-mac-home-server/README.md".text = ''
      # darwin-mac-home-server

      This directory is generated by nix-darwin.

      ## Installed with Homebrew

      - caddy
      - colima
      - docker
      - docker-compose
      - ffmpeg
      - filebrowser
      - jellyfin cask
      - jq
      - rclone
      - restic
      - rsync
      - smartmontools
      - tailscale
      - yq

      ## Runtime layout

      ```text
      ${cfg.serviceRoot}/compose.yaml
      ${cfg.serviceRoot}/Caddyfile
      ${cfg.serviceRoot}/state/
      ${cfg.serviceRoot}/backups/
      ${cfg.dataRoot}/Photos
      ${cfg.dataRoot}/Videos
      ${cfg.dataRoot}/Files
      ${cfg.backupRoot}
      ```

      ## Start containers

      ```bash
      cd ${cfg.serviceRoot}
      docker compose up -d
      ```

      Jellyfin is installed as a Homebrew cask. Start and configure the app,
      then point its libraries at `${cfg.dataRoot}/Videos` and
      `${cfg.dataRoot}/Photos`.

      ## Recommended access

      Use Tailscale for remote access first. Only expose Caddy publicly after
      TLS, authentication, and allowed hostnames are configured deliberately.
    '';

    system.activationScripts.homeServerScaffold.text = ''
      install -d -m 0755 -o ${user} -g staff ${lib.escapeShellArg cfg.serviceRoot}
      install -d -m 0755 -o ${user} -g staff ${lib.escapeShellArg "${cfg.serviceRoot}/state"}
      install -d -m 0755 -o ${user} -g staff ${lib.escapeShellArg "${cfg.serviceRoot}/backups"}

      ln -sfn /etc/darwin-mac-home-server/compose.yaml ${lib.escapeShellArg "${cfg.serviceRoot}/compose.yaml"}
      ln -sfn /etc/darwin-mac-home-server/Caddyfile ${lib.escapeShellArg "${cfg.serviceRoot}/Caddyfile"}
      ln -sfn /etc/darwin-mac-home-server/README.md ${lib.escapeShellArg "${cfg.serviceRoot}/README.md"}

      if [ -d ${lib.escapeShellArg cfg.dataRoot} ]; then
        install -d -m 0755 -o ${user} -g staff ${lib.escapeShellArg "${cfg.dataRoot}/Photos"}
        install -d -m 0755 -o ${user} -g staff ${lib.escapeShellArg "${cfg.dataRoot}/Videos"}
        install -d -m 0755 -o ${user} -g staff ${lib.escapeShellArg "${cfg.dataRoot}/Files"}
      else
        echo "Skipping home-server data directories because ${cfg.dataRoot} is not mounted"
      fi

      if [ -d ${lib.escapeShellArg cfg.backupRoot} ]; then
        install -d -m 0755 -o ${user} -g staff ${lib.escapeShellArg "${cfg.backupRoot}/home-server"}
      else
        echo "Skipping home-server backup directory because ${cfg.backupRoot} is not mounted"
      fi
    '';
  };
}
