#monitor=,preferred,auto,1

#z@nixos ~/n/n/h/t/zed (main)> lg
#z[I] taco@nixos ~/n/n/h/t/zed (main)> hyprctl monitors
#zMonitor DP-2 (ID 0):
#z	3840x2160@59.99700 at 0x0
#z	description: HP Inc. HP 27f 4k 3CM9341PZL
#z	make: HP Inc.
#z	model: HP 27f 4k
#z	serial: 3CM9341PZL
#z	active workspace: 1 (1)
#z	special workspace: 0 ()
#z	reserved: 0 0 0 24
#z	scale: 1.50
#z	transform: 0
#z	focused: yes
#z	dpmsStatus: 1
#z	vrr: false
#z	solitary: 0
#z	activelyTearing: false
#z	directScanoutTo: 0
#z	disabled: false
#z	currentFormat: XRGB8888
#z	mirrorOf: none
#z	availableModes: 3840x2160@60.00Hz 3840x2160@60.00Hz 3840x2160@59.94Hz 3840x2160@50.00Hz 3840x2160@29.97Hz 3840x2160@25.00Hz 3840x2160@23.98Hz 2560x1440@59.95Hz 1920x1200@59.88Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1920x1080@29.97Hz 1920x1080@25.00Hz 1920x1080@23.98Hz 1680x1050@59.95Hz 1600x900@60.00Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1366x768@60.00Hz 1280x800@74.93Hz 1280x800@59.81Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@60.00Hz 800x600@60.32Hz 720x576@50.00Hz #z720x480@59.94Hz 640x480@59.94Hz 640x480@59.93Hz
#z
#zMonitor HDMI-A-1 (ID 1):
#z	3840x2160@60.00000 at 2560x0
#z	description: Dell Inc. DELL S2721QS 13ZZM43
#z	make: Dell Inc.
#z	model: DELL S2721QS
#z	serial: 13ZZM43
#z	active workspace: 2 (2)
#z	special workspace: 0 ()
#z	reserved: 0 0 0 24
#z	scale: 1.50
#z	transform: 0
#z	focused: no
#z	dpmsStatus: 1
#z	vrr: false
#z	solitary: 0
#z	activelyTearing: false
#z	directScanoutTo: 0
#z	disabled: false
#z	currentFormat: XRGB8888
#z	mirrorOf: none
#z	availableModes: 3840x2160@60.00Hz 3840x2160@59.94Hz 3840x2160@29.97Hz 3840x2160@25.00Hz 3840x2160@23.98Hz 2560x1440@59.95Hz 2048x1280@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1920x1080@25.00Hz 1920x1080@23.98Hz 1600x1200@60.00Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1152x864@75.00Hz 1280x720@59.94Hz 1024x768@75.03Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@60.32Hz 720x576@50.00Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@59.94Hz 640x480@59.93Hz
#z

input {
  kb_layout = us
  follow_mouse = 1

  touchpad {
    natural_scroll = true
  }
}

general {
  gaps_in = 3
  gaps_out = 3
  border_size = 3
  col.active_border = rgba(33ccffee)
  col.inactive_border = rgba(595959aa)
  layout = dwindle
}

#decoration {
#  rounding = 10
#  blur = true
#  blur_size = 3
#  blur_passes = 1
#}

animations {
enabled = false
}

# --- key binds ------------------------------
$MOD = ALT
#bind = SHIFT CTRL, M, exec, alacritty
bind = CTRL SHIFT, K, exec, zeditor

env = NIXOS_OZONE_WL,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = QT_QPA_PLATFORM, wayland

# adujet vulkan for wayland for zed
env = VK_ICD_FILENAMES, /run/opengl-driver/share/vulkan/icd.d/nvidia_icd.x86_64.json
env = VK_LAYER_PATH, /run/opengl-driver/share/vulkan/explicit_layer.d
env = XDG_SESSION_TYPE , wayland
env = GBM_BACKEND, nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME, nvidia
env = XDG_CURRENT_DESKTOP, Hyprland

bind = CTRL SHIFT, SPACE, exec, env NIXOS_OZONE_WL=1 ELECTRON_OZONE_PLATFORM_HINT=wayland fuzzel -p "Go: "

bind = $MOD, F, fullscreenstate,1
bind = SHIFT $MOD, J, movefocus, l
bind = SHIFT $MOD, L, movefocus, r
bind = SHIFT $MOD, H, movefocus, d

bind = CTRL $MOD, J, movewindow, l
bind = CTRL $MOD, L, movewindow, r
bind = CTRL $MOD, H, movewindow, d
bind = CTRL SHIFT, Q, killactive,


# switch workspace
bind = SHIFT $MOD, 1, workspace, 1
bind = SHIFT $MOD, 2, workspace, 2
bind = SHIFT $MOD, 3, workspace, 3
bind = SHIFT $MOD, 4, workspace, 4
bind = SHIFT $MOD, 5, workspace, 5

# move windows to the workspace
bind = CTRL $MOD, 1, movetoworkspace, 1
bind = CTRL $MOD, 2, movetoworkspace, 2
bind = CTRL $MOD, 3, movetoworkspace, 3
bind = CTRL $MOD, 4, movetoworkspace, 4
bind = CTRL $MOD, 5, movetoworkspace, 5


exec-once = waybar

# screen sharing for zoom. not used?
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
