#monitor=,preferred,auto,1

input {
  kb_layout = us
  follow_mouse = 1

  touchpad {
    natural_scroll = true
  }
}

general {
  gaps_in = 3
  gaps_out = 3
  border_size = 3
  col.active_border = rgba(33ccffee)
  col.inactive_border = rgba(595959aa)
  layout = dwindle
}

#decoration {
#  rounding = 10
#  blur = true
#  blur_size = 3
#  blur_passes = 1
#}

animations {
enabled = false
}

# --- key binds ------------------------------
$MOD = ALT
#bind = SHIFT CTRL, M, exec, alacritty
bind = SHIFT CTRL, M, exec, alacritty

bind = ALT, Tab, exec, fuzzel -p "Go: "

bind = SHIFT $MOD, J, movefocus, l
bind = SHIFT $MOD, L, movefocus, r

bind = CTRL $MOD, J, movewindow, l
bind = CTRL $MOD, L, movewindow, r
bind = CTRL SHIFT, Q, killactive,


# switch workspace
bind = SHIFT $MOD, 1, workspace, 1
bind = SHIFT $MOD, 2, workspace, 2
bind = SHIFT $MOD, 3, workspace, 3
bind = SHIFT $MOD, 4, workspace, 4
bind = SHIFT $MOD, 5, workspace, 5

# move windows to the workspace
bind = CTRL $MOD, 1, movetoworkspace, 1
bind = CTRL $MOD, 2, movetoworkspace, 2
bind = CTRL $MOD, 3, movetoworkspace, 3
bind = CTRL $MOD, 4, movetoworkspace, 4
bind = CTRL $MOD, 5, movetoworkspace, 5

# 自動起動
exec-once = waybar
#exec-once = hyprpaper
